version: "3.9"
services:
  pingfederate:
    image: pingidentity/pingfederate:latest
    #- command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    command: entrypoint.sh start-server
    env_file:
    #  - ~/.pingidentity/devops
      - ./env_vars
    environment:
    - SERVER_PROFILE_URL=https://github.com/rborlone/pingidentity_solution.git
    - SERVER_PROFILE_PATH=profiles/pingfederate
    
    volumes:
    - /root/pingidentity_solution/licenses/licencias/PingFederate.lic:/opt/out/instance/server/default/conf/pingfederate.lic 
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    networks:
      - pingnet
    ports:
      - 9031:9031
      - 9999:9999
    restart: on-failure
    depends_on:
      - pingdirectory
  pingdirectory:
    image: pingidentity/pingdirectory:latest
    env_file:
    #  - ~/.pingidentity/devops
      - ./env_vars
    environment:
    - SERVER_PROFILE_URL=https://github.com/rborlone/pingidentity_solution.git
    - SERVER_PROFILE_PATH=profiles/pingdirectory

    volumes:
    - /root/pingidentity_solution/licenses/licencias/PingDirectory.lic:/opt/in/pd.profile/server-root/pre-setup/PingDirectory.lic 
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    networks:
      - pingnet
    ports:
      - 389:389
      - 1636:636
      - 1443:443
      - 2443:2443

  pingdataconsole:
    image: pingidentity/pingdataconsole:latest
    networks:
      - pingnet
    ports:
      - 8080:8080
      - 8443:8443
  
networks:
  pingnet: